spring.application.name=labtrack

spring.datasource.url=jdbc:postgresql://localhost:5432/labtrack
spring.datasource.username=labtrack
spring.datasource.password=labtrack

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
